### ISSUE TITLE
`+5` gives parsing error, but is valid R

### ISSUE THREAD

**Issue by lloyddewit** [lloyddewit/RScript#21]
![image](https://github.com/lloyddewit/RScript/assets/57253949/c906843a-9e5c-453b-9a85-96d50b87b4c8)

**Comment by rdstern** [comment]
@lloyddewit I am always looking for possible work-arounds.
a) I notice `-5` is ok.
b) I get the same message with `*5`.  However `(+5)` runs ok and (*5) does not!
